notifications:
email: false
language: c
before_install:
    - sudo add-apt-repository -y ppa:linaro-maintainers/toolchain
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-arm-none-eabi
compiler: gcc
script: make firmware
